from .config import (
    COR_CRITICO,
    COR_ALERTA,
    COR_OK,
    COR_INFO,
    COR_NEUTRO,
    TARIFA_MINIMA,
    CUSTO_UNITARIO_AGUA,
    FATOR_SUBMEDICAO,
    IDADE_HIDRO_CRITICA,
    MESES_ZERO_CRONICO,
    PLOTLY_TEMPLATE,
    COLOR_SEQUENCE,
    PREMISSAS,
)

__all__ = [
    'COR_CRITICO', 'COR_ALERTA', 'COR_OK', 'COR_INFO', 'COR_NEUTRO',
    'TARIFA_MINIMA', 'CUSTO_UNITARIO_AGUA', 'FATOR_SUBMEDICAO',
    'IDADE_HIDRO_CRITICA', 'MESES_ZERO_CRONICO',
    'PLOTLY_TEMPLATE', 'COLOR_SEQUENCE', 'PREMISSAS',
]